### ISSUE TITLE
[Resolved] 1.1.0 Fix causes launch crash

### ISSUE THREAD

**Issue by PanoptesDreams** [LemmaEOF/ShulkerCharm#3]
Game crashes immediately at launch

`---- Minecraft Crash Report ----
// My bad.

Time: 12/30/19 11:25 PM
Description: Initializing game

java.lang.NoClassDefFoundError: io/github/ladysnake/pal/Pal
	at space.bbkr.shulkercharm.ShulkerCharm.<clinit>(ShulkerCharm.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:100)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:92)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:143)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:391)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: io.github.ladysnake.pal.Pal
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at space.bbkr.shulkercharm.ShulkerCharm.<clinit>(ShulkerCharm.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:100)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:92)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:143)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:391)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by LemmaEOF** [comment]
what the hell?

**Comment by PanoptesDreams** [comment]
It's player ability lib

**Comment by LemmaEOF** [comment]
Yeah, I know. It's just that this should *absolutely* not happen, because I specifically told loom to include PAL so this doesn't happen. I'll find the jar for PAL; just putting it in your environment should fix this.

**Comment by LemmaEOF** [comment]
[This link](https://jitpack.io/com/github/ladysnake/PlayerAbilityLib/1.0.0/PlayerAbilityLib-1.0.0.jar) should have the fix. I'll whack at the project to see what the hell is going on tomorrow. If this *still* doesn't work, it's officially Not My Problem™.

**Comment by PanoptesDreams** [comment]
I got the jar, it's launching now. (https://github.com/Ladysnake/PlayerAbilityLib/releases)
I've been trying to diagnose it for about half an hour and been looking for the lib

**Comment by LemmaEOF** [comment]
Alright, good. Looks like this is just Loom messing up. I need to sleep for now but this means I can just publish a new version for now and it'll work without more code changes. I'll leave this issue open till the release is there.

**Comment by PanoptesDreams** [comment]
Resolved with  v1.1.0
